# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be6d0997335f0457191091053b68aa3e2fbc9e51d4510a957cd325e24e13616606f9e76c4c09e4f3c08eaf29fd250b9a8f1e0a7f4a552ba7b9fdd27fc544232a

test:
  secret_key_base: ecf1d7f4d5505b740c0c7ad13a70e8cbd00563f7badc4f6f43ac41c1b2fed923f6f1ed450cc7eba0fdc9fe710f83a4abb60d1c45cbd7bc9dd75a99224324acec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
